###
## Typus Configuration File
##
#
# Post:
#   fields:
#     list: id, title, category_id, created_at, status
#     form: title, body, status, created_at
#     relationship: title, status
#     options:
#       selectors:
#       read_only:
#       auto_generated:
#       questions:
#       date_formats:
#         created_at: post_long
#   actions:
#     index: cleanup
#     edit: send_as_newsletter
#     show: rebuild
#   order_by: created_at
#   relationships:
#   filters: status, created_at, category_id
#   search: title, body
#   application: Application
#   description: Some text to describe the model
#
###
<%- ar_models.each do |model| -%>
<%- list = model.columns.collect { |i| [ i.name, i.sql_type ] if i.sql_type != 'text' }.compact.map(&:first) -%>
<%- form = model.columns.collect { |i| [ i.name, i.sql_type ] if i.name != 'id' }.compact.map(&:first) -%>
<%- relationships = [ ] -%>
<%- [:belongs_to, :has_and_belongs_to_many, :has_many].each do |relationship| -%>
 <%- relationships += model.reflect_on_all_associations(relationship).map { |i| i.name.to_s } -%>
<%- end -%>

<%= model %>:
  fields:
    list: <%= list.map.join(', ') %>
    form: <%= form.map.join(', ') %>
    relationship:
    options:
      selectors:
      read_only:
      auto_generated:
      questions:
  actions:
    index:
    edit:
  order_by:
  relationships: <%= relationships.sort.join(', ') %>
  filters:
  search:
  application: <%= application %>
  description:
<%- end -%>